name: Run correlation analysis

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  run-analysis:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Upgrade pip and install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Create output folder
        run: mkdir -p output

      - name: Pick latest CSV
        id: pick
        shell: bash
        run: echo "CSV=$(ls -t data/*.csv | head -n 1)" >> "$GITHUB_OUTPUT"

      - name: Run correlation script
        run: python correlacion_github.py --input "${{ steps.pick.outputs.CSV }}" --output output

      - name: Upload results (artifact: resultados-correlacion)
        uses: actions/upload-artifact@v4
        with:
          name: resultados-correlacion
          path: output
